export const paragraphs = {
  low: [
    "The explorer visited the hermitage and recognised a similar talking bird, yet this bird talked respectfully and welcomed him to remain there.There was once a pleased elephant who generally harassed smaller animals. He would go to the ant colony and shower water on the ants.",
    "Every day he invested a lot of energy searching for food and looking at the skyline for Gods help. One day, when he returned from his food search, he found his little hut burnt to ashes.There was once a pleased elephant who generally harassed smaller animals. He would go to the ant colony and shower water on the ants.",
    "There was once a pleased elephant who generally harassed smaller animals. He would go to the ant colony and shower water on the ants.The elephant started crying in pain. He understood his mistake and apologised to the ants and every one of the animals he had harassed.There was once a pleased elephant.",
    "The elephant started crying in pain. He understood his mistake and apologised to the ants and every one of the animals he had harassed.There was once a pleased elephant who generally harassed smaller animals. He would go to the ant colony and shower water on the ants.",
    "Be humble and treat everybody with respect. If you think you are stronger than others, then use your solidarity to safeguard them instead of hurting them.There was once a pleased elephant who generally harassed smaller animals. He would go to the ant colony and shower water on the ants.",
  ],
  medium: [
    "Today, Doris had come to school ready for whatever came to mind. She’d thought to ask her fellow long timers what they suggested. Looking hopelessly around the group, however, she realized they would not have any suggestions for the new girl. Rather, she had rubbed off on them already. ",
    "It all started with a random letter. Several of those were joined forces to create a random word. The words decided to get together and form a random sentence. They decided not to stop there and it wasn't long before a random paragraph had been cobbled together. The question was whether or not they could continue the momentum long enough to create a random short story.",
    "After a long flight, a thirsty crow found itself in a forest, desperately seeking water. At last, it spotted a pot containing some water, but its beak couldn’t reach it. Not one to give up, the clever crow spotted some pebbles nearby. It placed these pebbles, one by one, into the pot until the water level rose enough for it to take a refreshing drink.",
    "Limit your hand and finger movement only to what is necessary to press a specific key. Keep your hands and fingers close to the base position. This improves typing speed and reduces stress on the hands.Do not rush when you just started learning. Speed up only when your fingers hit the right keys out of habit.Always scan the text a word or two in advance.",
    "Several hours later, a boat arrived at the shore, ready to rescue him. The man, bewildered, asked the ship’s captain, “How did you locate me?” To which the captain responded, “We spotted the smoke signal you unintentionally created, a cry for help.”This unexpected turn of events renewed the man’s faith in the mysterious ways of God.",
  ],
  hard: [
    "“Come on! It’s starting!” Greg, my neighbor, hollered from the sidewalk.“What’s starting?” I said. Behind him, groups of kids hurried down the street.  “The magic show!” said Greg, exasperated. “At Mr. Hale’s house!”“Just relax,” Mr. Hale whispered. “There’s nothing to it.” I got into the box and held my breath.White haired and very thin, Mr. Hale wore a black top-hat and tails. In his hand he gripped a wand, producing doves from an urn. He asked for a volunteer to be sawed in half. I raised my hand. No one breathed.",
    "“Got me,” I said, taking a look. Barney, our 18 pound Maine Coon, peered up at me with his yellow eyes. The cat had squeezed his massive frame through an opening in the wall that an animal half his size would have had trouble with. He was trapped.“What are we going to do?” said Amy. “We can’t just leave him there.”The cat let out a mournful meow.So, I brushed the tears away from her little cheeks and grabbed the hammer from the toolbox.",
    "This is the short story 'Burrito Man' which was taken from the Novel, 'Us in Progress: Short Stories About Young Latinos' by Lulu Delacre. The story is about a young girl (13 or so) who goes to work with her father who is a food cart vendor.The story is about a young girl (13 or so) who goes to work with her father who is a food cart vendor. She's embarrassed by him because of his job, but learns throughout the day how hard he works.",
    "It all be started with 123 and @&% type numbers and symbol.There was a boy named John who was so lazy he couldn't even change his clothes. One day, he saw the apple tree in their yard was full of fruits. 'He wanted to eat some apples, but he was too lazy to climb the tree and take the fruits. So he lay down underneath the tree and waited for the fruits to fall off'.A short story is a brief work of fiction, usually written in prose and running 1,600 to 20,000 words in length.",
    "For example , a 1,000 word short story might have around 5 to 10 paragraphs , while a 5,000 word short story might have around 10 to 15 paragraphs . Ultimately , the length of a short story is up to the author 's discretion and depends on the needs of the story . Intrigued to know more about the captivating world of short stories? Dive into the link in my bio for an in depth exploration of their structure , impact , and the art of crafting compelling narratives within these concise literary realms .",
  ],
}
